theme: jekyll-theme-slate
title: EdNiles.com
description: "Cruel jokes are a big part of life in any environment where speed freaks, work addicts, and obsessive-compulsive political junkies are ripped to the tits day and night for thirteen straight months on their own adrenaline" - Hunter S. Thompson
